/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author erikaekholm
 */
public class Hallbarhetsmalen extends javax.swing.JFrame {
    private final InfDB idb; 
    private final String aid;
    
    /**
     * Creates new form Hallbarhetsmalen
     * @param idb
     * @param aid
     */
    public Hallbarhetsmalen(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Stänger MinaUppgifterPopup när man trycker på krysset i rutan utan att stänga ner hela programmet
        laddaHallbarhetsMal(); // Öppnar fakta om Hållbarhetsmålen när rutan öppnas
    }
    
    public void laddaHallbarhetsMal(){
        // Hämtar hållbarhetsmålen ifrån databasen
        
        try{
            String query = "SELECT namn, malnummer, beskrivning FROM hallbarhetsmal";
            ArrayList<HashMap<String, String>> resultatHallbarhetsMal = idb.fetchRows(query);
            
            // Skapar en lista för hållbarhetsmålen ifrån default
            DefaultListModel<String> modellListan = new DefaultListModel<>();
            
            if(resultatHallbarhetsMal != null){
                for(HashMap<String, String> hallbarhetsmalen : resultatHallbarhetsMal){
                    String textenIRutan = hallbarhetsmalen.get("malnummer") + ": " + hallbarhetsmalen.get("namn") + " - " + hallbarhetsmalen.get("beskrivning");
                    modellListan.addElement(textenIRutan);
                }
            }
            // Lägger in listan i modellen i GUI
            lstHallbarhetsmal.setModel(modellListan);
            
        } catch(InfException ex){
            JOptionPane.showMessageDialog(this, "Inga Hållbarhetsmål hittades!" + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCirkelMal = new javax.swing.JLabel();
        jspHallbarhetsmal = new javax.swing.JScrollPane();
        lstHallbarhetsmal = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCirkelMal.setIcon(new javax.swing.ImageIcon("/Users/erikaekholm/Documents/GitHub/NGO_2/CirkelMal.png")); // NOI18N
        lblCirkelMal.setText("jLabel1");

        lstHallbarhetsmal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jspHallbarhetsmal.setViewportView(lstHallbarhetsmal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jspHallbarhetsmal, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblCirkelMal, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCirkelMal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspHallbarhetsmal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hallbarhetsmalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hallbarhetsmalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hallbarhetsmalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hallbarhetsmalen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Hallbarhetsmalen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspHallbarhetsmal;
    private javax.swing.JLabel lblCirkelMal;
    private javax.swing.JList<String> lstHallbarhetsmal;
    // End of variables declaration//GEN-END:variables
}
