/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author karin
 */
public class Inloggning extends javax.swing.JFrame {

    private InfDB idb; //Fält för att lagra databasuppkoppling
    private final Behorighet behorighet; // Objektet Behorighet är en instansvariabel
    /**
     * Creates new form Inloggning
     * @param idb
     */
    public Inloggning(InfDB idb) { // Det jag sickar in som parameter
        this.idb = idb;
        this.behorighet = new Behorighet(idb); // Lägger till behörighet ifrån klass
        initComponents();
        lblfelmeddelande.setVisible(false);
        setSize(500, 300); // Storlek på fönstret
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setLayout(null); // Sätter hela layouten på mitten av rutan
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblepost = new javax.swing.JLabel();
        lbllosenord = new javax.swing.JLabel();
        tfepost = new javax.swing.JTextField();
        btnloggain = new javax.swing.JButton();
        tflosenord = new javax.swing.JTextField();
        lblfelmeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblepost.setText("E-Post");
        getContentPane().add(lblepost);
        lblepost.setBounds(39, 73, 54, 20);

        lbllosenord.setText("Lösenord");
        getContentPane().add(lbllosenord);
        lbllosenord.setBounds(39, 102, 54, 20);
        getContentPane().add(tfepost);
        tfepost.setBounds(128, 70, 173, 23);

        btnloggain.setText("Logga in");
        btnloggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloggainActionPerformed(evt);
            }
        });
        getContentPane().add(btnloggain);
        btnloggain.setBounds(216, 163, 79, 23);

        tflosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflosenordActionPerformed(evt);
            }
        });
        getContentPane().add(tflosenord);
        tflosenord.setBounds(128, 99, 173, 23);

        lblfelmeddelande.setForeground(new java.awt.Color(255, 0, 0));
        lblfelmeddelande.setText("Felaktig Epost eller Lösenord");
        getContentPane().add(lblfelmeddelande);
        lblfelmeddelande.setBounds(39, 140, 256, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tflosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflosenordActionPerformed

    private void btnloggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloggainActionPerformed
        Behorighet behorighet = new Behorighet(idb);
        try{
            String losenDB = idb.fetchSingle("SELECT losenord FROM anstalld WHERE epost = '" + tfepost.getText() + "'");
        if(losenDB != null && losenDB.equals(tflosenord.getText())){
            String aid = behorighet.getAID(tfepost.getText());
            if(aid != null){
            if(behorighet.isProjektledare(aid)){
                new MenyProjektledare(idb, aid).setVisible(true);
            }else if(behorighet.isHandlaggare(aid)){
                new MenyHandlaggare(idb, aid).setVisible(true);
            }else{
                new Meny(idb, aid).setVisible(true);
            }
            this.setVisible(false); // Stänger inloggningsfönstret
        } else {
            lblfelmeddelande.setText("Fel lösenord eller e-post");
            lblfelmeddelande.setVisible(true);
            }
        }}catch(InfException ex){
            System.out.println("Fel vid hämtning av Anställd" + ex.getMessage());
                 }
    }//GEN-LAST:event_btnloggainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
        //        //new Inloggning().setVisible(true);
        //    }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloggain;
    private javax.swing.JLabel lblepost;
    private javax.swing.JLabel lblfelmeddelande;
    private javax.swing.JLabel lbllosenord;
    private javax.swing.JTextField tfepost;
    private javax.swing.JTextField tflosenord;
    // End of variables declaration//GEN-END:variables

}
