/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author karin
 */
public class Inloggning extends javax.swing.JFrame {

    private final InfDB idb; //Fält för att lagra databasuppkoppling
    /**
     * Creates new form Inloggning
     * @param idb
     */
    public Inloggning(InfDB idb) { // Det jag sickar in som parameter
        this.idb = idb;
        initComponents();
        lblfelmeddelande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblepost = new javax.swing.JLabel();
        lbllosenord = new javax.swing.JLabel();
        tfepost = new javax.swing.JTextField();
        btnloggain = new javax.swing.JButton();
        tflosenord = new javax.swing.JTextField();
        lblfelmeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblepost.setText("E-Post");

        lbllosenord.setText("Lösenord");

        btnloggain.setText("Logga in");
        btnloggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloggainActionPerformed(evt);
            }
        });

        tflosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflosenordActionPerformed(evt);
            }
        });

        lblfelmeddelande.setForeground(new java.awt.Color(255, 0, 0));
        lblfelmeddelande.setText("Felaktig Epost eller Lösenord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnloggain)
                            .addComponent(lblfelmeddelande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblepost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbllosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfepost, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(tflosenord)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblepost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tfepost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tflosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbllosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(lblfelmeddelande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnloggain)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tflosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflosenordActionPerformed

    private void btnloggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloggainActionPerformed
        
        String ePost = tfepost.getText(); // Lagrar lokal variabel användarens E-post
        String losen = tflosenord.getText(); // Lagrar lokal variabel användarens lösenord
        // try är om man vill göra något inom databasen
        try{
            // SQL frågor för att först kolla att lösenord och e-post matchar hos anställd
            String dbLosen = idb.fetchSingle("SELECT losenord FROM anstalld WHERE epost = '" + ePost + "'");
            // Om lösenordet inte är = null och dbLosen (lokal parameter) stämmer
            if(dbLosen != null && losen.equals(dbLosen)){
            // Om lösenordet är korrekt - hämta AID ifrån anställd tabell
            String aid = idb.fetchSingle("SELECT AID FROM anstalld WHERE epost = '" + ePost + "'");
            
            //Här nedan kommer if satsen baserad på om anställd är handläggare eller inte
            if(aid != null){ // Först kollar vi att aid inte är lika med null
                String aidHandläggare = idb.fetchSingle("SELECT COUNT(*) FROM handlaggare WHERE AID = '" + aid + "'");
                // Om AID finns i handläggare tabellen; öppna MenyHandläggare, annars öppna Meny
                if("0".equals(aidHandläggare)){ // Om AID finns i handlaggare; öppna MenyHandläggare - annars öppna Meny
                    new Meny(idb, aid).setVisible(true); // Öppnar Meny
                } else {
                    new MenyHandlaggare(idb, aid).setVisible(true);
                }
            } this.setVisible(false); // Dölj inloggningsfönstret
            } else {
            lblfelmeddelande.setText("Anställd eller ePost hittades inte");
            lblfelmeddelande.setVisible(true);
            }
        }catch(InfException ex){
                    System.out.println("Inloggningsfel: " + ex.getMessage());
                    }
            
    }//GEN-LAST:event_btnloggainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
        //    public void run() {
        //        //new Inloggning().setVisible(true);
        //    }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnloggain;
    private javax.swing.JLabel lblepost;
    private javax.swing.JLabel lblfelmeddelande;
    private javax.swing.JLabel lbllosenord;
    private javax.swing.JTextField tfepost;
    private javax.swing.JTextField tflosenord;
    // End of variables declaration//GEN-END:variables

}
