/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.HashMap;
import javax.swing.*;

/**
 *
 * @author erikaekholm
 */
public class LaggTillAnstalldAdmin extends javax.swing.JFrame {
    private final InfDB idb;
    private final String aid;
    
    /**
     * Creates new form LaggTillAnstalldAdmin
     */
    public LaggTillAnstalldAdmin(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        setLayout(null);
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Stänger MinaUppgifterPopup när man trycker på krysset i rutan utan att stänga ner hela programmet
        
    // Tomma textfält till att börja med
    txtAidLaggTill.setText("");
    txtFornamnLaggTill.setText("");
    txtEfternamnLaggTill.setText("");
    txtAdressLaggTill.setText("");
    txtEpostLaggTill.setText("");
    txtTelefonLaggTill.setText("");
    txtSlumpatLosenLaggTill.setText("");
    setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAidLaggTill = new javax.swing.JTextField();
        lblLaggTillNyAnstalld = new javax.swing.JLabel();
        txtFornamnLaggTill = new javax.swing.JTextField();
        txtEfternamnLaggTill = new javax.swing.JTextField();
        txtAdressLaggTill = new javax.swing.JTextField();
        txtEpostLaggTill = new javax.swing.JTextField();
        txtTelefonLaggTill = new javax.swing.JTextField();
        txtSlumpatLosenLaggTill = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnSlumpaNyttLosenord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAidLaggTill.setText("AID");

        lblLaggTillNyAnstalld.setText("Lägg till en ny anställd");

        txtFornamnLaggTill.setText("Förnamn");

        txtEfternamnLaggTill.setText("Efternamn");

        txtAdressLaggTill.setText("Adress");

        txtEpostLaggTill.setText("Epost");

        txtTelefonLaggTill.setText("Telefon");

        txtSlumpatLosenLaggTill.setText("Lösenord");

        jButton1.setText("Spara ny Anställd");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSlumpaNyttLosenord.setText("Slumpa nytt lösenord");
        btnSlumpaNyttLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlumpaNyttLosenordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLaggTillNyAnstalld, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSlumpatLosenLaggTill)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSlumpaNyttLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTelefonLaggTill, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEpostLaggTill, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdressLaggTill, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEfternamnLaggTill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtFornamnLaggTill, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAidLaggTill, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLaggTillNyAnstalld)
                .addGap(26, 26, 26)
                .addComponent(txtAidLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFornamnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEfternamnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdressLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEpostLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSlumpatLosenLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlumpaNyttLosenord))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSlumpaNyttLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlumpaNyttLosenordActionPerformed
        // TODO add your handling code here:
        // Slumpar fram nytt lösenord i textrutan txtLosenordAdminSlumpa
        String losenord = metodSlumpaLosenordAdmin(7); // Genererar lösenordet - Här har vi valt att det slumpade lösenordet kommer ha 7 tecken.
        txtSlumpatLosenLaggTill.setText(losenord); // Visar lösenordet i textfältet och sedan kan användaren Admin trycka på spara knappen
    }//GEN-LAST:event_btnSlumpaNyttLosenordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
        String aid = txtAidLaggTill.getText();
        String fornamn = txtFornamnLaggTill.getText();
        String efternamn = txtEfternamnLaggTill.getText();
        String adress = txtAdressLaggTill.getText();
        String epost = txtEpostLaggTill.getText();
        String telefon = txtTelefonLaggTill.getText();
        
        if(aid.isEmpty() || fornamn.isEmpty() || efternamn.isEmpty() || adress.isEmpty() || epost.isEmpty() || telefon.isEmpty()){
            JOptionPane.showMessageDialog(this, "Fyll i alla uppgifter för ny Anställd!", "Fel", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            String query = "INSERT INTO anstalld(aid, fornamn, efternamn, adress, epost, telefon, losenord) VALUES ('"
                    + aid + "', '" + fornamn + "', '" + efternamn + "', '" + adress + "', '" + epost + "', '"
                    + telefon + "')";
            idb.insert(query);
            JOptionPane.showMessageDialog(this, "Ny användare tillagd! ", "Lyckades", JOptionPane.INFORMATION_MESSAGE);
        } catch(InfException ex){
            JOptionPane.showMessageDialog(this, "Fel vid inmatning av uppgifter! ", "Fel", JOptionPane.ERROR_MESSAGE);
        }    
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private String metodSlumpaLosenordAdmin(int langdPaLosenord){
        String genereraLosenord = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"; // Sträng skapas som innehåller alla möjliga tecken som losenordet kan ha
        String losenord = ""; // Strängen tom ifrån början
        
        for(int index = 0; index < langdPaLosenord; index++){ // Loopar langdPaLosenord antal ggr och genererar ett slumpat tecken varje loop
            int randomIndex =(int) (Math.random() * genereraLosenord.length()); // Math.random ger ett slumpmässigt tal
            losenord += genereraLosenord.charAt(randomIndex); // Hämtar tecken på ett av positionerna i genereraLosenord och lägger i strängen
        }
        return losenord; // 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new LaggTillAnstalldAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSlumpaNyttLosenord;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblLaggTillNyAnstalld;
    private javax.swing.JTextField txtAdressLaggTill;
    private javax.swing.JTextField txtAidLaggTill;
    private javax.swing.JTextField txtEfternamnLaggTill;
    private javax.swing.JTextField txtEpostLaggTill;
    private javax.swing.JTextField txtFornamnLaggTill;
    private javax.swing.JTextField txtSlumpatLosenLaggTill;
    private javax.swing.JTextField txtTelefonLaggTill;
    // End of variables declaration//GEN-END:variables
}
