/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.HashMap;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author erikaekholm
 */
public class LaggTillHandlaggareProjektledare extends javax.swing.JFrame {
    private final InfDB idb;
    private final String aid;
    
    /**
     * Creates new form LaggTillHandlaggareProjektledare
     * @param idb
     * @param aid
     */
    public LaggTillHandlaggareProjektledare(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        setLayout(null);
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        laddaProjektchefensProjekt();
        laddaHandlaggare();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Stänger MinaUppgifterPopup när man trycker på krysset i rutan utan att stänga ner hela programmet
        
        // Lägger till den användare som är inloggad direkt under lblinloggadanvandare
        try{
            String query = "SELECT fornamn, efternamn FROM anstalld WHERE aid = '" + aid + "'";
            HashMap<String, String> resultat = idb.fetchRow(query);
            
            if(resultat != null){
                lblInloggadAnvandare.setText("Inloggad som: " + resultat.get("fornamn") + " " + resultat.get("efternamn"));
            } else {
                lblInloggadAnvandare.setText("inloggad som: Okänd");
            }
        } catch(InfException ex){
            lblInloggadAnvandare.setText("Fel vid hämtning av användarnamn!");
            System.out.println("Fel vid hämtning av användarnamn" + ex.getMessage());
        }
    }
    
        private void laddaProjektchefensProjekt(){
    
        try{
            jcbValjProjekt.removeAllItems(); // Tar bort gamla objekt
            String query = "SELECT projektnamn FROM projekt WHERE projektchef = " + aid;
            ArrayList<String> projektNamnLista = idb.fetchColumn(query);

        if (projektNamnLista != null) {
            for (String projektnamn : projektNamnLista) {
                jcbValjProjekt.addItem(projektnamn);
            }
        }
        } catch(InfException ex){
            System.out.println("Fel vid laddning av projekt: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Fel vid laddning av pjojekt! ", "Fel", JOptionPane.ERROR_MESSAGE);
        }
    }
        
        private void laddaHandlaggare(){
        try {
            String query = "SELECT CONCAT(fornamn, ' ', efternamn) AS namn FROM anstalld JOIN handlaggare ON anstalld.aid = handlaggare.aid";
            ArrayList<String> partnerLista = idb.fetchColumn(query);

        if (partnerLista != null) {
            jlistHandlaggarlista.setListData(partnerLista.toArray(new String[0]));
        }
            } catch (InfException ex) {
        System.out.println("Fel vid laddning av Handläggare: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Fel vid laddning av Handläggare! ", "Fel", JOptionPane.ERROR_MESSAGE);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        jcbValjProjekt = new javax.swing.JComboBox<>();
        jScrHandlaggarlista = new javax.swing.JScrollPane();
        jlistHandlaggarlista = new javax.swing.JList<>();
        btnLaggTillHandlaggare = new javax.swing.JButton();
        lblValjBlandDinaProjekt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("Inloggad användare SDG Sweden");

        jScrHandlaggarlista.setViewportView(jlistHandlaggarlista);

        btnLaggTillHandlaggare.setText("Lägg till Handläggare");
        btnLaggTillHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillHandlaggareActionPerformed(evt);
            }
        });

        lblValjBlandDinaProjekt.setText("Välj projekt du vill addera Handläggare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLaggTillHandlaggare)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblValjBlandDinaProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                .addComponent(jcbValjProjekt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(51, 51, 51)
                            .addComponent(jScrHandlaggarlista, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblInloggadAnvandare)
                .addGap(49, 49, 49)
                .addComponent(lblValjBlandDinaProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbValjProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrHandlaggarlista, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnLaggTillHandlaggare)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillHandlaggareActionPerformed
        // TODO add your handling code here:
        
        try {
        String valtProjekt = jcbValjProjekt.getSelectedItem().toString(); 
        List<String> valdaHandlaggare = jlistHandlaggarlista.getSelectedValuesList();

        if (valtProjekt.isEmpty() || valdaHandlaggare.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Välj ett projekt och en handläggare du vill lägga till!", "Fel", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Hämta projektets ID från dess namn
        String projektQuery = "SELECT pid FROM projekt WHERE projektnamn = '" + valtProjekt + "'";
        String projektIdStr = idb.fetchSingle(projektQuery);
        int projektId = Integer.parseInt(projektIdStr);
       
        for (String handlaggareNamn : valdaHandlaggare) {
            // Hämta handläggarens ID från dess namn
            String handlaggarQuery = "SELECT aid FROM anstalld WHERE CONCAT(fornamn, ' ', efternamn) = '" + handlaggareNamn + "'";
            String handlaggareIdStr = idb.fetchSingle(handlaggarQuery);
            int handlaggareId = Integer.parseInt(handlaggareIdStr);
            
            // Kontrollera om handläggaren redan är kopplad till projektet så vi undviker dubletter
            String kollaQuery = "SELECT COUNT(*) FROM ans_proj WHERE pid = " + projektId + " AND aid = " + handlaggareId; // count räknar antalet rader som matchar frågan
            String countStr = idb.fetchSingle(kollaQuery);
            int count = Integer.parseInt(countStr);
            
            if (count == 0) {
                // Lägg till ny handläggare i projektet
                String insertQuery = "INSERT INTO ans_proj (pid, aid) VALUES (" + projektId + ", " + handlaggareId + ")";
                idb.insert(insertQuery);
                JOptionPane.showMessageDialog(this, "Handläggare " + handlaggareNamn + " har lagts till i projekt " + valtProjekt, "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Handläggare " + handlaggareNamn + " är redan kopplad till projektet " + valtProjekt, "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    } catch (InfException ex) {
        System.out.println("Fel vid sparning av handläggare: " + ex.getMessage());
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Fel vid sparning av handläggare!", "Fel", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_btnLaggTillHandlaggareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggareProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggareProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggareProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillHandlaggareProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //    new LaggTillHandlaggareProjektledare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillHandlaggare;
    private javax.swing.JScrollPane jScrHandlaggarlista;
    private javax.swing.JComboBox<String> jcbValjProjekt;
    private javax.swing.JList<String> jlistHandlaggarlista;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblValjBlandDinaProjekt;
    // End of variables declaration//GEN-END:variables
}
