/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.HashMap;
import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author erikaekholm
 */
public class LaggTillPartnerAdmin extends javax.swing.JFrame {
    private final InfDB idb;
    private final String aid;
    
    /**
     * Creates new form LaggTillPartnerAdmin
     */
    public LaggTillPartnerAdmin(InfDB idb, String aid) {
       this.idb = idb;
        this.aid = aid;
        initComponents();
        setLayout(null);
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Stänger MinaUppgifterPopup när man trycker på krysset i rutan utan att stänga ner hela programmet
        laddaNyttPartnerID();
        laddaBrancher();
        laddaStader();
        
    // Tomma textfält till att börja med
    txtPartnerID.setEditable(false);
    txtpartnerNamn.setText("");
    txtKontaktperson.setText("");
    txtEpost.setText("");
    txtTelefon.setText("");
    txtAdress.setText("");
    setVisible(true);
    }
    
public void laddaNyttPartnerID(){
    //SQL för högsta numret pid
        try {
        // SQL-fråga för att hitta det senaste (högsta) projekt-ID
        String query = "SELECT MAX(pid) FROM partner";
        String senastePidStr = idb.fetchSingle(query); 

        int nyttPid = 1; // Om inga projekt finns, starta från 1

        if (senastePidStr != null) {
            nyttPid = Integer.parseInt(senastePidStr) + 1; // Nästa lediga ID
        }

        //Visa det nya projekt-ID:t i txtpid, dvs ladda i txtpid
        txtPartnerID.setText(String.valueOf(nyttPid));
        txtPartnerID.setVisible(true);

    } catch (InfException ex) {
        System.out.println("Fel vid hämtning av partner-ID: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av partner-ID!", "Fel", JOptionPane.ERROR_MESSAGE);
    }
    }
        
public void laddaStader(){
        try {
        String query = "SELECT sid FROM stad"; // Hämtar unika länder
        ArrayList<String> stadLista = idb.fetchColumn(query);

        if (stadLista != null) {
            jcbStad.removeAllItems(); // Rensar gamla val
            for (String land : stadLista) {
                jcbStad.addItem(land); // Lägg till länderna i ComboBoxen
            }
        }
    } catch (InfException ex) {
        System.out.println("Fel vid hämtning av länder: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av länder!", "Fel", JOptionPane.ERROR_MESSAGE);
    }
    }
            
public void laddaBrancher(){
            try {
        String query = "SELECT branch FROM partner"; // Hämtar brancher
        ArrayList<String> branchLista = idb.fetchColumn(query);

        if (branchLista != null) {
            jcbBranch.removeAllItems(); // Rensar gamla val
            for (String branch : branchLista) {
                jcbBranch.addItem(branch); // Lägg till brancherna i ComboBoxen
            }
        }
    } catch (InfException ex) {
        System.out.println("Fel vid hämtning av brancher: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av brancher!", "Fel", JOptionPane.ERROR_MESSAGE);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbStad = new javax.swing.JComboBox<>();
        btnSparaNyPartner = new javax.swing.JButton();
        lblLand = new javax.swing.JLabel();
        jcbBranch = new javax.swing.JComboBox<>();
        lblBranch = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        txtEpost = new javax.swing.JTextField();
        lblEpost = new javax.swing.JLabel();
        lblKontaktperson = new javax.swing.JLabel();
        txtKontaktperson = new javax.swing.JTextField();
        lblPartnerNamn = new javax.swing.JLabel();
        txtpartnerNamn = new javax.swing.JTextField();
        txtPartnerID = new javax.swing.JTextField();
        lblPartnerID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSparaNyPartner.setText("Spara ny Partner");
        btnSparaNyPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaNyPartnerActionPerformed(evt);
            }
        });

        lblLand.setText("Land");

        lblBranch.setText("Branch");

        txtAdress.setText("Adress");

        lblAdress.setText("Adress");

        txtTelefon.setText("Telefon");

        lblTelefon.setText("Telefon");

        txtEpost.setText("Epost");

        lblEpost.setText("E-post");

        lblKontaktperson.setText("Kontaktperson");

        txtKontaktperson.setText("Kontaktperson");

        lblPartnerNamn.setText("Partner Namn");

        txtpartnerNamn.setText("PartnerNamn");

        txtPartnerID.setText("Partner ID");

        lblPartnerID.setText("Partner-ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSparaNyPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPartnerID)
                    .addComponent(txtEpost)
                    .addComponent(txtTelefon)
                    .addComponent(txtAdress)
                    .addComponent(jcbBranch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcbStad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKontaktperson, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(txtpartnerNamn))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblLand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblEpost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelefon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(lblAdress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBranch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lblKontaktperson, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPartnerNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(lblPartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPartnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPartnerID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPartnerNamn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpartnerNamn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKontaktperson, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKontaktperson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLand))
                .addGap(53, 53, 53)
                .addComponent(btnSparaNyPartner)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaNyPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaNyPartnerActionPerformed
        // TODO add your handling code here:
         int nyttPid = Integer.parseInt(txtPartnerID.getText());
        String namn = txtpartnerNamn.getText();
        String kontaktperson = txtKontaktperson.getText();
        String kontaktepost = txtEpost.getText();
        String telefon = txtTelefon.getText();
        String adress = txtAdress.getText();
        String valdBranch = jcbBranch.getSelectedItem().toString();
        String valdStad = jcbStad.getSelectedItem().toString();

        try {
        //Skapa SQL-fråga utan `pid`
        String query = "INSERT INTO partner(pid, namn, kontaktperson, kontaktepost, telefon, adress, branch, stad) VALUES ("
                        + nyttPid + ", '" + namn + "', '" + kontaktperson + "', '" 
                        + kontaktepost + "', '" + telefon + "', '" 
                        + adress + "', '" + valdBranch + "', "
                        + valdStad + ")";
        
        idb.insert(query);
        
         //Hämta senaste ID från databasen med `LAST_INSERT_ID()`
        String nyttPidQuery = "SELECT LAST_INSERT_ID()";
        String senastePid = idb.fetchSingle(nyttPidQuery);
        
       //Se till att `senastePid` inte är null
        if (senastePid != null) {
            txtPartnerID.setText(senastePid); // Visa det nya projekt-ID:t i txtpid
            System.out.println("Senaste PID: " + senastePid); // Debugging
        } else {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av partner-ID!", "Fel", JOptionPane.ERROR_MESSAGE);
        }

        JOptionPane.showMessageDialog(this, "Partnern har lagts till!", "Lyckades", JOptionPane.INFORMATION_MESSAGE);

    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Fel vid inmatning av partner!", "Fel", JOptionPane.ERROR_MESSAGE);
        System.out.println("Fel vid partner-skapning: " + ex.getMessage());
        ex.printStackTrace();
    }    
        
        
        
        
    }//GEN-LAST:event_btnSparaNyPartnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillPartnerAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new LaggTillPartnerAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaNyPartner;
    private javax.swing.JComboBox<String> jcbBranch;
    private javax.swing.JComboBox<String> jcbStad;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblKontaktperson;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblPartnerID;
    private javax.swing.JLabel lblPartnerNamn;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtKontaktperson;
    private javax.swing.JTextField txtPartnerID;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtpartnerNamn;
    // End of variables declaration//GEN-END:variables
}
