/**
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 * Gemensamma rubriker på alla menyer:
"Mina Uppgifter" – Se och ändra egna uppgifter - DONE
"Projekt" – Se projekt man är tilldelad på - DONE
"Partners" – Se vilka samarbetspartners som finns i projekten
"Hållbarhetsmål" – Se en lista över hållbarhetsmålen - DONE
"Personal" – Se och söka efter personal på avdelningen
"Sök projekt" – Sök efter projekt baserat på datum
"Logga ut" – För att logga ut från systemet
* 
 * @author karin
 */
public class MenyHandlaggare extends javax.swing.JFrame {

    private final InfDB idb; 
    private final String aid;
  
    public MenyHandlaggare(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        
        initComponents(); // Skrivs här för att använda sig av NetBeans GUI komponenter
        // setSize(1250, 1750); // Storlek på fönstret - tog bort och fixar GUI istället
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setLayout(null); // Sätter hela layouten i mitten av rutan
        
        // Lägger till den användare som är inloggad direkt under lblinloggadanvandare
        try{
            String query = "SELECT fornamn, efternamn FROM anstalld WHERE aid = '" + aid + "'";
            HashMap<String, String> resultat = idb.fetchRow(query);
            
            if(resultat != null){
                lblinloggadanvandare.setText("Inloggad som: " + resultat.get("fornamn") + " " + resultat.get("efternamn"));
            } else {
                lblinloggadanvandare.setText("Inloggad som: Okänd");
            }
        
        } catch(InfException ex){
            lblinloggadanvandare.setText("Fel vid hämtning av användarnamn!");
            System.out.println("Fel vid hämtning av användarnamn" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblinloggadanvandare = new javax.swing.JLabel();
        btnMinaProjektHandlaggare = new javax.swing.JButton();
        btnMinaUppgifterHandlaggare = new javax.swing.JButton();
        btnMinAvdelning = new javax.swing.JButton();
        btnAllaMal = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblinloggadanvandare.setText("Inloggad SDG Sweden");

        btnMinaProjektHandlaggare.setText("Projekt");
        btnMinaProjektHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjektHandlaggareActionPerformed(evt);
            }
        });

        btnMinaUppgifterHandlaggare.setText("Mina Uppgifter");
        btnMinaUppgifterHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaUppgifterHandlaggareActionPerformed(evt);
            }
        });

        btnMinAvdelning.setText("Avdelning");
        btnMinAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinAvdelningActionPerformed(evt);
            }
        });

        btnAllaMal.setIcon(new javax.swing.ImageIcon("/Users/erikaekholm/Documents/GitHub/NGO_2/SUSDEVALL.jpg")); // NOI18N
        btnAllaMal.setSelectedIcon(new javax.swing.ImageIcon("/Users/erikaekholm/Desktop/GlobalaMålenBilder/Globala1.jpg")); // NOI18N
        btnAllaMal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllaMalActionPerformed(evt);
            }
        });

        btnPersonal.setText("Personal");
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblinloggadanvandare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMinaUppgifterHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinaProjektHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnAllaMal, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblinloggadanvandare)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMinaUppgifterHandlaggare)
                        .addGap(15, 15, 15)
                        .addComponent(btnMinaProjektHandlaggare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMinAvdelning)
                        .addGap(18, 18, 18)
                        .addComponent(btnPersonal))
                    .addComponent(btnAllaMal, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnMinaProjektHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektHandlaggareActionPerformed
        // TODO add your handling code here:
        // Öppnar popup fönster med projekt relevanta för handläggaren
        new MinaProjektPopup(idb, aid).setVisible(true);
    }//GEN-LAST:event_btnMinaProjektHandlaggareActionPerformed

    private void btnMinAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinAvdelningActionPerformed
        // TODO add your handling code here:
        new MinAvdelning(idb, aid).setVisible(true);
    }//GEN-LAST:event_btnMinAvdelningActionPerformed

    private void btnMinaUppgifterHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterHandlaggareActionPerformed
        // TODO add your handling code here:
        new MinaUppgifterPopup(idb, aid).setVisible(true); // Öppnar MinaUppgifterPopup
    }//GEN-LAST:event_btnMinaUppgifterHandlaggareActionPerformed

    private void btnAllaMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllaMalActionPerformed
        // TODO add your handling code here:
        new Hallbarhetsmalen(idb, aid).setVisible(true); // Öppnar Hallbarhetsmalen
    }//GEN-LAST:event_btnAllaMalActionPerformed

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        // TODO add your handling code here:
        new PersonalAvdelning(idb, aid).setVisible(true);
    }//GEN-LAST:event_btnPersonalActionPerformed

    private static class ex {

        private static String getMessage() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public ex() {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new Meny().setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllaMal;
    private javax.swing.JButton btnMinAvdelning;
    private javax.swing.JButton btnMinaProjektHandlaggare;
    private javax.swing.JButton btnMinaUppgifterHandlaggare;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JLabel lblinloggadanvandare;
    // End of variables declaration//GEN-END:variables
}