/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JFrame;

/**
  *Gemensamma rubriker på alla menyer:
"Min profil" – Se och ändra egna uppgifter - DONE
"Projekt" – Se projekt man är tilldelad på
"Partners" – Se vilka samarbetspartners som finns i projekten
"Hållbarhetsmål" – Se en lista över hållbarhetsmålen
"Personal" – Se och söka efter personal på avdelningen
"Sök projekt" – Sök efter projekt baserat på datum
"Logga ut" – För att logga ut från systemet
 
 *Rubriker för MenyProjektledare
"Hantera projekt" – Ändra uppgifter om projekt
"Hantera partners" – Lägg till/ta bort partners i projekt
"Hantera handläggare" – Lägg till/ta bort handläggare i projekt
"Projektstatistik" – Se kostnadsstatistik över projekt
 * @author erikaekholm
 */
public class MenyProjektledare extends javax.swing.JFrame {
    private final InfDB idb;
    private final String aid;
    
    /**
     * Creates new form MenyProjektledare
     * @param idb
     * @param aid
     */
    public MenyProjektledare(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents(); // Skrivs här för att använda sig av NetBeans GUI komponenter
        setSize(1250, 1750); // Storlek på fönstret
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setLayout(null); // Sätter hela layouten i mitten av rutan
        
        // Lägger till den användare som är inloggad direkt under lblinloggadanvandare
        try{
            String query = "SELECT fornamn, efternamn FROM anstalld WHERE aid = '" + aid + "'";
            HashMap<String, String> resultat = idb.fetchRow(query);
            
            if(resultat != null){
                lblinloggadanvandare2.setText("Inloggad som: " + resultat.get("fornamn") + " " + resultat.get("efternamn"));
            } else {
                lblinloggadanvandare2.setText("inloggad som: Okänd");
            }
        } catch(InfException ex){
            lblinloggadanvandare2.setText("Fel vid hämtning av användarnamn!");
            System.out.println("Fel vid hämtning av användarnamn" + ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinaUppgifterProjektledare = new javax.swing.JButton();
        lblinloggadanvandare2 = new javax.swing.JLabel();
        btnMinaProjektProjektledare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMinaUppgifterProjektledare.setText("Mina Uppgifter");
        btnMinaUppgifterProjektledare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaUppgifterProjektledareActionPerformed(evt);
            }
        });

        lblinloggadanvandare2.setText("Inloggad användare SDG Sweden");

        btnMinaProjektProjektledare.setText("Mina Projekt");
        btnMinaProjektProjektledare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjektProjektledareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblinloggadanvandare2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMinaUppgifterProjektledare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinaProjektProjektledare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblinloggadanvandare2)
                .addGap(29, 29, 29)
                .addComponent(btnMinaUppgifterProjektledare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinaProjektProjektledare)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaUppgifterProjektledareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterProjektledareActionPerformed
        // TODO add your handling code here:
        new MinaUppgifterPopup(idb, aid).setVisible(true); // Öppnar MinaUppgifterPopup
    }//GEN-LAST:event_btnMinaUppgifterProjektledareActionPerformed

    private void btnMinaProjektProjektledareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektProjektledareActionPerformed
        // TODO add your handling code here:
        new MinaProjektPopup(idb, aid).setVisible(true); // Öppnar mina MinaProjektPopup
    }//GEN-LAST:event_btnMinaProjektProjektledareActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinaProjektProjektledare;
    private javax.swing.JButton btnMinaUppgifterProjektledare;
    private javax.swing.JLabel lblinloggadanvandare2;
    // End of variables declaration//GEN-END:variables

        private static class ex {

        private static String getMessage() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public ex() {
        }
    }
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
           //new MenyProjektledare(idb, aid).setVisible(true);
            
           }
        });
    }}


    
    
        
               
                         
