/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JFrame;

/**
 *
 * @author karin
 */
public class MenyHandlaggare extends javax.swing.JFrame {

    private final InfDB idb; 
    private final String aid;
  
    public MenyHandlaggare(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        setSize(1250, 1750); // Storlek på fönstret
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setLayout(null); // Sätter hela layouten i mitten av rutan
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblinloggadanvandare = new javax.swing.JLabel();
        MinaUppgifterHandlaggare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblinloggadanvandare.setText("Hello World");

        MinaUppgifterHandlaggare.setText("Mina Uppgifter");
        MinaUppgifterHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinaUppgifterHandlaggareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblinloggadanvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(MinaUppgifterHandlaggare)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblinloggadanvandare)
                .addGap(26, 26, 26)
                .addComponent(MinaUppgifterHandlaggare)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinaUppgifterHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinaUppgifterHandlaggareActionPerformed
        // TODO add your handling code here:
        // Öppnar popup fönster med information om användaren
        try{
            String query = "SELECT fornamn, efternamn, adress, epost, telefon FROM anstalld WHERE aid = '" + aid + "'"; // Sql frågan emot databasen
            // Hämta en rad ifrån databasen och lagrar som Hashmap för att komma åt nyckeln
            HashMap<String, String> resultat = idb.fetchRow(query);
            if(resultat != null){
            // Skapa ett nytt JFrame som popup
            JFrame popupMinaUppgifter = new JFrame("Mina Uppgifter");
            popupMinaUppgifter.setSize(300, 200); // Sätt storlek på fönstret
            setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
            setLayout(null); // Sätter hela layouten i mitten av rutan
            popupMinaUppgifter.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Stänger fönstret men behåller programmet öppet

            // Kollar igenom resultatet för visning
            String textMinaUppgifter = "<html>";
            for(String nyckel : resultat.keySet()){
                textMinaUppgifter += nyckel + ": " + resultat.get(nyckel) + "<br>";
            }
            textMinaUppgifter += "</html>";


            // Skapa en JLabel för att visa användarens uppgifter
            JLabel infoMinaUppgifter = new JLabel(textMinaUppgifter);
            popupMinaUppgifter.add(infoMinaUppgifter); // Lägg till texten i fönstret
            // Visar popup-fönster med mina uppgifter
            popupMinaUppgifter.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Ingen data hittades för användaren: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
            }
        
        }catch(InfException ex){
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av data: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_MinaUppgifterHandlaggareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new Meny().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MinaUppgifterHandlaggare;
    private javax.swing.JLabel lblinloggadanvandare;
    // End of variables declaration//GEN-END:variables

    private static class ex {

        private static String getMessage() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public ex() {
        }
    }
}
