/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JFrame;

/**
 *Gemensamma rubriker på alla menyer:
"Mina Uppgifter" – Se och ändra egna uppgifter - DONE
"Projekt" – Se projekt man är tilldelad på - DONE
"Partners" – Se vilka samarbetspartners som finns i projekten - DONE
"Hållbarhetsmål" – Se en lista över hållbarhetsmålen - DONE
"Personal" – Se och söka efter personal på avdelningen
"Sök projekt" – Sök efter projekt baserat på datum
"Logga ut" – För att logga ut från systemet - DONE
* 
* * Rubriker för Meny (administratör)
"Anställda" – Lägg till/ta bort en anställd
"Generera lösenord" – Skapa slumpmässigt lösenord för ny anställd
"Hantera avdelningar" – Lägg till/ändra uppgifter för avdelningar
"Hantera projekt" – Lägg till/ändra projekt och ansvariga
"Hantera partners" – Lägg till/ändra uppgifter om partners
"Hantera länder" – Lägg till/ändra uppgifter om länder
* 
* 
 * @author karin
 */
public class Meny extends javax.swing.JFrame {

    private final InfDB idb; 
    private final String aid;
  
    public Meny(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents(); // Skrivs här för att använda sig av NetBeans GUI komponenter
        // setSize(1250, 1750); // Storlek på fönstret
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setLayout(null); // Sätter hela layouten i mitten av rutan
        
                // Lägger till den användare som är inloggad direkt under lblinloggadanvandare
        try{
            String query = "SELECT fornamn, efternamn FROM anstalld WHERE aid = '" + aid + "'";
            HashMap<String, String> resultat = idb.fetchRow(query);
            
            if(resultat != null){
                lblinloggadanvandare3.setText("Inloggad som: " + resultat.get("fornamn") + " " + resultat.get("efternamn"));
            } else {
                lblinloggadanvandare3.setText("inloggad som: Okänd");
            }
        } catch(InfException ex){
            lblinloggadanvandare3.setText("Fel vid hämtning av användarnamn!");
            System.out.println("Fel vid hämtning av användarnamn" + ex.getMessage());
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinaProjektAdmin = new javax.swing.JButton();
        lblinloggadanvandare3 = new javax.swing.JLabel();
        btnMinaUppgifterAdmin = new javax.swing.JButton();
        btnAllaMal = new javax.swing.JButton();
        btnProjekt = new javax.swing.JButton();
        btnAvdelning = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnHanteraAnstalld = new javax.swing.JButton();
        btnHanteraAvdelningar = new javax.swing.JButton();
        btnHanteraProjekt = new javax.swing.JButton();
        btnHanteraPartners = new javax.swing.JButton();
        lblHallbarhetsmalenRubrik = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();

        btnMinaProjektAdmin.setText("Mina Projekt");
        btnMinaProjektAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjektAdminActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(50, 50));

        lblinloggadanvandare3.setText("Inloggad användare SDG Sweden");

        btnMinaUppgifterAdmin.setText("Mina Uppgifter");
        btnMinaUppgifterAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaUppgifterAdminActionPerformed(evt);
            }
        });

        btnAllaMal.setIcon(new javax.swing.ImageIcon("/Users/erikaekholm/Documents/GitHub/NGO_2/SUSDEVALL.jpg")); // NOI18N
        btnAllaMal.setText("jButton1");
        btnAllaMal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllaMalActionPerformed(evt);
            }
        });

        btnProjekt.setText("Projekt");

        btnAvdelning.setText("Avdelning");

        btnPersonal.setText("Personal");

        btnHanteraAnstalld.setText("Hantera Anställd");

        btnHanteraAvdelningar.setText("Hantera Avdelningar");

        btnHanteraProjekt.setText("Hantera Projekt");

        btnHanteraPartners.setText("Hantera Partners");

        lblHallbarhetsmalenRubrik.setText("Klicka på bilden för att se Hållbarhetsmålen vi jobbar för!");

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblinloggadanvandare3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblHallbarhetsmalenRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMinaUppgifterAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHanteraAnstalld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHanteraAvdelningar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHanteraProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHanteraPartners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(btnAllaMal, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoggaUt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblinloggadanvandare3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHallbarhetsmalenRubrik)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAllaMal, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMinaUppgifterAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(btnProjekt)
                        .addGap(18, 18, 18)
                        .addComponent(btnAvdelning)
                        .addGap(18, 18, 18)
                        .addComponent(btnPersonal)
                        .addGap(81, 81, 81)
                        .addComponent(btnHanteraAnstalld)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHanteraAvdelningar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHanteraProjekt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHanteraPartners)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoggaUt)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaUppgifterAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterAdminActionPerformed
        // TODO add your handling code here:
        new MinaUppgifterPopup(idb, aid).setVisible(true);
    }//GEN-LAST:event_btnMinaUppgifterAdminActionPerformed

    private void btnMinaProjektAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektAdminActionPerformed
        // TODO add your handling code here:
        new MinaProjektPopup(idb, aid).setVisible(true);
    }//GEN-LAST:event_btnMinaProjektAdminActionPerformed

    private void btnAllaMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllaMalActionPerformed
        // TODO add your handling code here:
        new Hallbarhetsmalen(idb, aid).setVisible(true); // Öppnar Hallbarhetsmalen
    }//GEN-LAST:event_btnAllaMalActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        // TODO add your handling code here:
        new Inloggning(idb).setVisible(true); // Öppnar inloggningsfönstret
        dispose(); // Rensar och stänger fönstret som är öppet korrekt
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Meny().setVisible(true);
            }
        });
    }
    
        private static class ex {

        private static String getMessage() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public ex() {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllaMal;
    private javax.swing.JButton btnAvdelning;
    private javax.swing.JButton btnHanteraAnstalld;
    private javax.swing.JButton btnHanteraAvdelningar;
    private javax.swing.JButton btnHanteraPartners;
    private javax.swing.JButton btnHanteraProjekt;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnMinaProjektAdmin;
    private javax.swing.JButton btnMinaUppgifterAdmin;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JLabel lblHallbarhetsmalenRubrik;
    private javax.swing.JLabel lblinloggadanvandare3;
    // End of variables declaration//GEN-END:variables
}

