/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author karin
 */
    public class NyttProjekt extends javax.swing.JFrame {

       
        private InfDB idb;
        private AnvandareBehorighet anvandareBehorighet;

    public NyttProjekt(InfDB idb, AnvandareBehorighet anvandareBehorighet) {
        initComponents();
        this.idb = idb;
        this.anvandareBehorighet = anvandareBehorighet;
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        lblProjektnamn = new javax.swing.JLabel();
        txtProjektnamn = new javax.swing.JTextField();
        lblBeskrivning = new javax.swing.JLabel();
        txtBeskrivning = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        lblLand = new javax.swing.JLabel();
        txtLand = new javax.swing.JTextField();
        lblKostnad = new javax.swing.JLabel();
        txtKostnad = new javax.swing.JTextField();
        lblPrio = new javax.swing.JLabel();
        txtPrio = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblProjektchef = new javax.swing.JLabel();
        txtProjektchef = new javax.swing.JTextField();
        btnSparastang = new javax.swing.JButton();
        lblPid = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHead.setText("Skapa nytt Projekt");

        lblProjektnamn.setText("Projektnamn");

        txtProjektnamn.setText("Projektnamn");

        lblBeskrivning.setText("Beskrivning");

        txtBeskrivning.setText("Beskrivning");

        lblFrom.setText("Från Datum");

        txtFrom.setText("YYYY-MM-DD");

        lblTo.setText("Till Datum");

        txtTo.setText("YYYY-MM-DD");

        lblLand.setText("Land");

        txtLand.setText("Land (lid)");

        lblKostnad.setText("Kostnad");

        txtKostnad.setText("SEK");

        lblPrio.setText("Prioritet");

        txtPrio.setText(" Låg, Medel, Hög");

        lblStatus.setText("Status");

        txtStatus.setText("Planerat, Pågående, Avslutat");

        lblProjektchef.setText("Projektchef");

        txtProjektchef.setText("Projektchef (aid)");

        btnSparastang.setText("Spara och Stäng");
        btnSparastang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparastangActionPerformed(evt);
            }
        });

        lblPid.setText("ProjektID");

        txtPid.setText("Välj siffra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLand, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblPrio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblKostnad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtLand, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProjektnamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBeskrivning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPid)
                                    .addComponent(txtProjektnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(txtBeskrivning))))
                        .addContainerGap(220, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSparastang)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHead, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPid)
                    .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProjektnamn)
                    .addComponent(txtProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBeskrivning)
                    .addComponent(txtBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLand)
                    .addComponent(txtLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKostnad)
                    .addComponent(txtKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrio)
                    .addComponent(txtPrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjektchef)
                    .addComponent(txtProjektchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSparastang))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparastangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparastangActionPerformed

        String pid = txtPid.getText().trim();
        String projektnamn = txtProjektnamn.getText().trim();
        String startdatum = txtFrom.getText().trim();
        String slutdatum = txtTo.getText().trim();
        String kostnad = txtKostnad.getText().trim();
        String status = txtStatus.getText().trim();
        String prioritet = txtPrio.getText().trim();
        String beskrivning = txtBeskrivning.getText().trim();
        String land = txtLand.getText().trim();
        String projektchef = txtProjektchef.getText().trim();

    StringBuilder felmeddelanden = new StringBuilder();

    if (!Validering.arText(projektnamn)) {
        felmeddelanden.append("Projektnamn får bara innehålla bokstäver och siffror.\n");
    }

    if (!Validering.arDatum(startdatum)) {
        felmeddelanden.append("Startdatum måste vara i formatet YYYY-MM-DD.\n");
    }

    if (!Validering.arDatum(slutdatum)) {
        felmeddelanden.append("Slutdatum måste vara i formatet YYYY-MM-DD.\n");
    }

    if (Validering.arDatum(startdatum) && Validering.arDatum(slutdatum)) {
        if (startdatum.compareTo(slutdatum) > 0) {
            felmeddelanden.append("Slutdatum kan inte vara före startdatum.\n");
        }
    }

    if (!Validering.arKostnad(kostnad)) {
        felmeddelanden.append("Kostnad måste vara ett heltal.\n");
    }

    if (!Validering.arText(land)) {
        felmeddelanden.append("Land får bara innehålla bokstäver.\n");
    }

    if (!Validering.arKostnad(projektchef)) {
        felmeddelanden.append("Projektchef måste vara ett heltal (aid).\n");
    }

    if (felmeddelanden.length() > 0) {
        JOptionPane.showMessageDialog(this, felmeddelanden.toString(), "Fel i inmatning", JOptionPane.WARNING_MESSAGE);
        return;
    }

        try {

            String kontrollSql = "SELECT aid FROM handlaggare WHERE aid = '" + projektchef + "'";
            String giltigProjektchef = idb.fetchSingle(kontrollSql);

            if (giltigProjektchef == null) {
                JOptionPane.showMessageDialog(this, "Projektchefen måste vara en giltig handläggare (aid).", "Fel", JOptionPane.ERROR_MESSAGE);
                return;
            }

        String sql = "INSERT INTO projekt (pid, projektnamn, startdatum, slutdatum, kostnad, status, prioritet, beskrivning, land, projektchef) "
                   + "VALUES ('" + pid + "','" + projektnamn + "', '" + startdatum + "', '" + slutdatum + "', '" + kostnad + "', '"
                   + status + "', '" + prioritet + "', '" + beskrivning + "', '" + land + "', '" + projektchef + "')";
        
        idb.insert(sql);

        JOptionPane.showMessageDialog(this, "Projektet har sparats och fönstret stängs.");
        this.dispose(); // STÄNGER FÖNSTRET

    } catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Ett fel uppstod: " + e.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_btnSparastangActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NyttProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NyttProjekt().setVisible(true);
//            }
//        });
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparastang;
    private javax.swing.JLabel lblBeskrivning;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblPid;
    private javax.swing.JLabel lblPrio;
    private javax.swing.JLabel lblProjektchef;
    private javax.swing.JLabel lblProjektnamn;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextField txtBeskrivning;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtKostnad;
    private javax.swing.JTextField txtLand;
    private javax.swing.JTextField txtPid;
    private javax.swing.JTextField txtPrio;
    private javax.swing.JTextField txtProjektchef;
    private javax.swing.JTextField txtProjektnamn;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
