/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author karin
 */
public class ProjektVy extends javax.swing.JFrame {

private InfDB idb;
    /**
     * Creates new form ProjektVy
     */
    public ProjektVy(InfDB idb) {
        this.idb = idb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjektTabell = new javax.swing.JTable();
        btnHamtaProjekt = new javax.swing.JButton();
        lblMinaProjekt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProjektTabell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProjektTabell);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnHamtaProjekt.setText("Hämta Projekt");
        btnHamtaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamtaProjektActionPerformed(evt);
            }
        });
        getContentPane().add(btnHamtaProjekt, java.awt.BorderLayout.PAGE_START);

        lblMinaProjekt.setText("Mina Projekt");
        getContentPane().add(lblMinaProjekt, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHamtaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamtaProjektActionPerformed
            // Skapa en arrayList för att hålla projektnamn:
            ArrayList<String> projektNamn;
            try{
                String sqlFraga = "SELECT projektnamn FROM projekt JOIN ans_proj ON projekt.pid = ans_proj.pid WHERE ans_proj.aid = 1";
                projektNamn = idb.fetchColumn(sqlFraga);//Hämta data från databasen och sparar i listan. 
                
                //Skapa en tabellmodell som fylls med data: (Klass som finns i Swing, används för att hålla data i JTable. 
                DefaultTableModel model = new DefaultTableModel();
                //Lägger till en kolumnrubrik i tabellen med namnet "Projektnamn"
                model.addColumn("Projektnamn");
                // Loopar listan 
                for (String namn : projektNamn) {
                    model.addRow(new Object[]{namn});
                }
                tblProjektTabell.setModel(model);//Visar den nya tabellen och kopplar till tblProjektTabell
            }catch (Exception ex){ 

            }
    }//GEN-LAST:event_btnHamtaProjektActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektVy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            //new ProjektVy().setVisible(true);
            }
        });
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHamtaProjekt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMinaProjekt;
    private javax.swing.JTable tblProjektTabell;
    // End of variables declaration//GEN-END:variables
}
