/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdgsweden;

import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.HashMap;
import javax.swing.*;

/**
 *
 * @author erikaekholm
 */
public class TaBortAnstalldAnstalldAdmin extends javax.swing.JFrame {
    private final InfDB idb;
    private final String aid;
    
    /**
     * Creates new form HanteraAnstalldAdmin
     * @param idb
     * @param aid
     */
    public TaBortAnstalldAnstalldAdmin(InfDB idb, String aid) {
        this.idb = idb;
        this.aid = aid;
        initComponents();
        setLayout(null);
        setLocationRelativeTo(null); // Fönstret hamnar i mitten av datorskärmen
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Stänger MinaUppgifterPopup när man trycker på krysset i rutan utan att stänga ner hela programmet
    
    // Tomma textfält till att börja med
    txtFornamnAdmin.setText("");
    txtEfternamnAdmin.setText("");
    txtAdressAdmin.setText("");
    txtEpostAdmin.setText("");
    txtTelefonAdmin.setText("");
    setVisible(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFornamnAdmin = new javax.swing.JTextField();
        txtEfternamnAdmin = new javax.swing.JTextField();
        txtAdressAdmin = new javax.swing.JTextField();
        txtEpostAdmin = new javax.swing.JTextField();
        txtTelefonAdmin = new javax.swing.JTextField();
        btnSokAnstalldAdmin = new javax.swing.JButton();
        txtSokAnstalldAdmin = new javax.swing.JTextField();
        btnTaBortAnstalldAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFornamnAdmin.setText("Förnamn");

        txtEfternamnAdmin.setText("Efternamn");

        txtAdressAdmin.setText("Adress");

        txtEpostAdmin.setText("E-post");

        txtTelefonAdmin.setText("Telefon");

        btnSokAnstalldAdmin.setText("Sök Anställd via ID");
        btnSokAnstalldAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokAnstalldAdminActionPerformed(evt);
            }
        });

        txtSokAnstalldAdmin.setText("Sökfält ID");

        btnTaBortAnstalldAdmin.setText("Ta bort Anställd");
        btnTaBortAnstalldAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortAnstalldAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEpostAdmin)
                            .addComponent(txtAdressAdmin)
                            .addComponent(txtTelefonAdmin)
                            .addComponent(txtSokAnstalldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFornamnAdmin)
                            .addComponent(txtEfternamnAdmin))
                        .addGap(29, 29, 29)
                        .addComponent(btnSokAnstalldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaBortAnstalldAdmin)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSokAnstalldAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSokAnstalldAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFornamnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEfternamnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAdressAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEpostAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnTaBortAnstalldAdmin)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokAnstalldAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokAnstalldAdminActionPerformed
        // TODO add your handling code here:
        // Knapp för att söka efter anställd via aid
        String sokaAnstalld = txtSokAnstalldAdmin.getText(); // Hämtar anställd som skrivs in i textfältet vi skapade
        
        try {
            String query = "SELECT fornamn, efternamn, adress, epost, telefon, losenord FROM anstalld WHERE aid = '" + sokaAnstalld + "'";
            HashMap<String, String> hittadAnstalld = idb.fetchRow(query);
            
            if(hittadAnstalld != null){
            // Dvs om Hittad Anställd inte är lika med null, fyll i fälten enligt nedan
            txtFornamnAdmin.setText(hittadAnstalld.get("fornamn"));
            txtEfternamnAdmin.setText(hittadAnstalld.get("efternamn"));            
            txtAdressAdmin.setText(hittadAnstalld.get("adress"));            
            txtEpostAdmin.setText(hittadAnstalld.get("epost"));            
            txtTelefonAdmin.setText(hittadAnstalld.get("telefon"));  
            
            } else { 
            // Dvs om ingen anställd hittades, behåll fälten som tomma och ge felmeddelande enligt JOptionPane (Swing versionen av System.out etc)
                  txtFornamnAdmin.setText("");
                  txtEfternamnAdmin.setText("");
                  txtAdressAdmin.setText("");
                  txtEpostAdmin.setText("");
                  txtTelefonAdmin.setText("");
                  JOptionPane.showMessageDialog(this, "Ingen anställd hittades med det AID!", "Fel", JOptionPane.ERROR_MESSAGE);
            }
        
        } catch(InfException ex){
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av Anställds uppgifter!", "Fel", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSokAnstalldAdminActionPerformed

    private void btnTaBortAnstalldAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortAnstalldAdminActionPerformed
        // TODO add your handling code here:
        String taBortAid = txtSokAnstalldAdmin.getText();  // Hämta AID att ta bort ifrån den Aid som vi sökt upp
        
        if(taBortAid.isEmpty()){
            JOptionPane.showMessageDialog(this, "Du måste först söka efter den anställda du vill ta bort ur databasen!", "Fel", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Vill du ta bort anställd med AID " + taBortAid + "?", "Bekräfta borttagning", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
        try{
        // SQL frågan för att ta bort användaren baserat på aid
        String query = "DELETE FROM anstalld WHERE aid = '" + taBortAid + "'";
        idb.delete(query);
        JOptionPane.showMessageDialog(this, "Användaren som har AID " + taBortAid + " har tagits bort ur databasen!", "Borttagning lyckades", JOptionPane.INFORMATION_MESSAGE );
        
        // Tömmer fälten efter borttagning
        txtSokAnstalldAdmin.setText("");
        txtFornamnAdmin.setText("");
        txtEfternamnAdmin.setText("");
        txtAdressAdmin.setText("");
        txtEpostAdmin.setText("");
        txtTelefonAdmin.setText("");
        
        } catch(InfException ex){
            JOptionPane.showMessageDialog(this, "Borttagning av användare misslyckades!", "Fel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTaBortAnstalldAdminActionPerformed
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalldAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalldAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalldAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortAnstalldAnstalldAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new TaBortAnstalldAnstalldAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSokAnstalldAdmin;
    private javax.swing.JButton btnTaBortAnstalldAdmin;
    private javax.swing.JTextField txtAdressAdmin;
    private javax.swing.JTextField txtEfternamnAdmin;
    private javax.swing.JTextField txtEpostAdmin;
    private javax.swing.JTextField txtFornamnAdmin;
    private javax.swing.JTextField txtSokAnstalldAdmin;
    private javax.swing.JTextField txtTelefonAdmin;
    // End of variables declaration//GEN-END:variables
}
